name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        npm ci
    - name: Update README
      env:
        LASTFM_KEY: ${{ secrets.LASTFM_KEY }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        LFMUSERNAME: ${{ secrets.LFMUSERNAME }}
      run: |-
        npm start
        cat README.md
    - name: Commit and push if changed
      run: |-
        git pull
        git add .
        git diff
        git config --global user.email "github-action-bot@example.com"
        git config --global user.name "Josh's Pet Cat"
        git commit -m "Updated README" -a || echo "No changes to commit"
        git push
